### ISSUE TITLE
Fix issues with H1 tags

### ISSUE THREAD

**Issue by 0xble** [0xble/host-and-home-cleaners-website#1]
# Motivation

Improve on-site SEO.

# Solution

- Fix duplicate H1s.
- Confirm each H1 represents the page's main topic.

**Comment by vats147** [comment]
I saw issue on replit.
Should i start working on this?

**Comment by 0xble** [comment]
> I saw issue on replit. Should i start working on this?

Hey @vats147, I appreciate your interest! I already selected someone for the bounty, but if they don't manage to do it or I have other issues in the future definitely apply again.

**Comment by vats147** [comment]
sure @0xble Tag me on github or ping me on [Portfolio Link](https://linktr.ee/vats147)
